bins:
	rm bin/hello_arm64 bin/simple_for
	aarch64-linux-gnu-gcc -O0 hello_arm64.c -o hello_arm64 --static
	aarch64-linux-gnu-gcc -O0 simple_for.c -o simple_for --static
	mv hello_arm64 simple_for bin/


