hists:
	python plot_dep.py -f whet100B -histv -x 100 -y 4000000 -s
	python plot_dep.py -f gcc100B  -histv -x 100 -y 4000000 -s
	python plot_dep.py -f mcf100B  -histv -x 100 -y 4000000 -s
	python plot_dep.py -f lbm100B  -histv -x 100 -y 4000000 -s

cumuls:
	python plot_dep.py -f whet100B -cumul -x 100 -s
	python plot_dep.py -f gcc100B  -cumul -x 100 -s
	python plot_dep.py -f mcf100B  -cumul -x 100 -s
	python plot_dep.py -f lbm100B  -cumul -x 100 -s

diffhists:
	python plot_diff.py -f whet100B -histv -x 100 -s
	python plot_diff.py -f gcc100B  -histv -x 100 -s
	python plot_diff.py -f mcf100B  -histv -x 100 -s
	python plot_diff.py -f lbm100B  -histv -x 100 -s

diffcumuls:
	python plot_diff.py -f whet100B -cumul -x 100 -s
	python plot_diff.py -f gcc100B  -cumul -x 100 -s
	python plot_diff.py -f mcf100B  -cumul -x 100 -s
	python plot_diff.py -f lbm100B  -cumul -x 100 -s